#!/usr/bin/env python3
"""Fix jj's auto-generated push-xxxx branch names and add stacked PR numbering.

This script detects bookmarks with the pattern `push-[a-z]{12}` (generated by
`jj git push --change`) and renames them to meaningful names based on the
commit description.

For stacked PRs, branch names include position (e.g., feat/topic-3) and
suggested PR titles include [topic][3/5] format.

Usage:
    python3 fix_branch_name.py [--dry-run] [--bookmark <name>]
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional

# Pattern for jj-generated push branches: push-<12 lowercase letters>
PUSH_BRANCH_PATTERN = re.compile(r"^push-[a-z]{12}$")

# Conventional commit pattern: type(scope): description OR type: description
CONVENTIONAL_COMMIT_PATTERN = re.compile(
    r"^(?P<prefix>feat|fix|docs|chore|refactor|test|style|perf|ci|build|revert)"
    r"(?:\([^)]+\))?:\s*(?P<title>.+)$",
    re.IGNORECASE,
)


def run_command(command: list[str], check: bool = True) -> str:
    """Runs a command and returns its stdout."""
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=check)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error running command {' '.join(command)}: {e.stderr}", file=sys.stderr)
        if check:
            raise
        return ""


def is_push_branch(name: str) -> bool:
    """Returns True if name matches jj's auto-generated push-xxxx pattern."""
    return bool(PUSH_BRANCH_PATTERN.match(name))


def parse_commit_description(description: str) -> tuple[str, str]:
    """Extracts prefix and title from a commit description.

    Returns:
        Tuple of (prefix, title). Defaults to ('feat', 'untitled') if parsing fails.
    """
    if not description or not description.strip():
        return ("feat", "untitled")

    description = description.strip()

    # Try to match conventional commit format
    match = CONVENTIONAL_COMMIT_PATTERN.match(description)
    if match:
        return (match.group("prefix").lower(), match.group("title").strip())

    # Default: assume it's a feature with the whole description as title
    return ("feat", description)


def slugify_title(title: str) -> str:
    """Convert title to a URL/branch-safe slug.

    - Converts to lowercase
    - Replaces spaces and special chars with hyphens
    - Removes leading/trailing hyphens
    - Truncates to max 40 chars
    """
    # Remove common prefixes that might be duplicated
    title = re.sub(
        r"^(feat|fix|docs|chore|refactor|test|style|perf|ci|build|revert)(\([^)]+\))?:\s*",
        "",
        title,
        flags=re.IGNORECASE,
    )

    # Convert to lowercase
    slug = title.lower()

    # Replace non-alphanumeric with hyphens
    slug = re.sub(r"[^a-z0-9]+", "-", slug)

    # Remove leading/trailing hyphens
    slug = slug.strip("-")

    # Truncate to reasonable length (40 chars max)
    if len(slug) > 40:
        # Try to truncate at a word boundary
        slug = slug[:40].rsplit("-", 1)[0]

    return slug


def get_current_bookmark_info(bookmark_name: Optional[str] = None) -> Optional[dict]:
    """Gets info about the current commit's bookmark.

    Returns a dict with keys: id, bookmarks, description, parents
    """
    # Template for jj log output: builds JSON object per commit
    # Using triple quotes to avoid escaping issues
    template = (
        '"{\\"id\\":\\"" ++ change_id ++ "\\", '
        '\\"bookmarks\\": [" ++ bookmarks.map(|b| "\\"" ++ b ++ "\\"").join(",") ++ "], '
        '\\"description\\": \\"" ++ description.first_line() ++ "\\", '
        '\\"parents\\": [" ++ parents.map(|p| "\\"" ++ p.change_id() ++ "\\"").join(",") ++ "]}"'
    )

    if bookmark_name:
        revset = f'bookmarks("{bookmark_name}")'
    else:
        revset = "@"

    try:
        output = run_command(["jj", "log", "-r", revset, "-T", template, "--no-graph"])
        if output.strip():
            return json.loads(output.strip())
    except (json.JSONDecodeError, subprocess.CalledProcessError):
        pass
    return None


def get_stack_info() -> tuple[int, int]:
    """Get the current commit's position in a stack.

    Returns:
        Tuple of (position, total). Position is 1-indexed from the base.
        Returns (1, 1) for non-stacked commits.
    """
    # Find all bookmarked commits that are ancestors of current commit
    # and descendants of main/master
    try:
        template = 'change_id ++ "\\n"'
        output = run_command(
            [
                "jj",
                "log",
                "-r",
                "ancestors(@, 2) & bookmarks()",
                "-T",
                template,
                "--no-graph",
            ],
            check=False,
        )

        if not output.strip():
            return (1, 1)

        count = len([line for line in output.split("\n") if line.strip()])
        return (count, count)  # Simplified: assumes we're at the top
    except subprocess.CalledProcessError:
        return (1, 1)


def get_stack_position(_bookmark_name: str) -> tuple[int, int]:
    """Get the position of a bookmark in a stack.

    Args:
        _bookmark_name: Name of the bookmark (currently unused, reserved for future use)

    Returns:
        Tuple of (position, total). Position is 1-indexed from the base.
    """
    return get_stack_info()


def generate_branch_name(prefix: str, topic: str, position: int, total: int) -> str:
    """Generate a meaningful branch name.

    Args:
        prefix: Conventional commit prefix (feat, fix, docs, etc.)
        topic: Slugified topic name
        position: Position in stack (1-indexed)
        total: Total commits in stack

    Returns:
        Branch name like 'feat/user-auth' or 'feat/s3-upload-3'
    """
    prefix = prefix.lower()

    if total > 1:
        return f"{prefix}/{topic}-{position}"
    else:
        return f"{prefix}/{topic}"


def generate_pr_title(
    prefix: str, title: str, topic: str, position: int, total: int
) -> str:
    """Generate a PR title with topic and optional stack numbering.

    Args:
        prefix: Conventional commit prefix
        title: Original commit title
        topic: Slugified topic name
        position: Position in stack (1-indexed)
        total: Total commits in stack

    Returns:
        PR title like 'feat: [add-user-login] Add user login' or
        'feat: [raw-memory-upload][4/5] Added implementation for s3 MPU start'
    """
    if total > 1:
        return f"{prefix}: [{topic}][{position}/{total}] {title}"
    else:
        return f"{prefix}: [{topic}] {title}"


def generate_pr_info(bookmark_name: Optional[str] = None) -> Optional[dict]:
    """Generate PR info as a dictionary for JSON output.

    Returns:
        Dict with keys: branch, title, topic, position, total
        Returns None if no push-xxxx bookmark found.
    """
    info = get_current_bookmark_info(bookmark_name)

    if not info:
        return None

    bookmarks = info.get("bookmarks", [])
    if not bookmarks:
        return None

    current_bookmark = bookmarks[0]

    if not is_push_branch(current_bookmark):
        return None

    description = info.get("description", "")
    prefix, title = parse_commit_description(description)
    topic = slugify_title(title)
    position, total = get_stack_position(current_bookmark)

    new_branch = generate_branch_name(prefix, topic, position, total)
    pr_title = generate_pr_title(prefix, title, topic, position, total)

    return {
        "branch": new_branch,
        "title": pr_title,
        "topic": topic,
        "position": position,
        "total": total,
        "old_bookmark": current_bookmark,
    }


def write_pr_info_to_file(pr_info: dict, output_path: str) -> None:
    """Write PR info to a JSON file.

    Args:
        pr_info: Dictionary containing PR metadata
        output_path: Path to write JSON file (will be validated)
    """
    # Use pathlib for safer path handling
    safe_path = Path(output_path).resolve()
    with safe_path.open("w") as f:
        json.dump(pr_info, f, indent=2)


def rename_bookmark(old_name: str, new_name: str, dry_run: bool = False) -> bool:
    """Rename a jj bookmark.

    Returns True if successful.
    """
    print(f"Renaming bookmark '{old_name}' -> '{new_name}'...")

    if dry_run:
        print(f"[Dry Run] Would run: jj bookmark rename {old_name} {new_name}")
        return True

    try:
        run_command(["jj", "bookmark", "rename", old_name, new_name])
        print(f"✅ Renamed '{old_name}' to '{new_name}'")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to rename: {e}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Fix jj's auto-generated push-xxxx branch names."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be changed without making changes.",
    )
    parser.add_argument(
        "--bookmark",
        type=str,
        help="Specific bookmark to check/fix (default: current commit's bookmark).",
    )
    parser.add_argument(
        "--json", action="store_true", help="Output PR info as JSON to stdout."
    )
    parser.add_argument(
        "--output", type=str, help="Write PR info to a JSON file at this path."
    )
    args = parser.parse_args()

    # JSON mode: use generate_pr_info and output
    if args.json or args.output:
        pr_info = generate_pr_info(args.bookmark)

        if not pr_info:
            if args.json:
                print("{}", file=sys.stdout)
            return

        if args.output:
            write_pr_info_to_file(pr_info, args.output)
            print(f"✅ Wrote PR info to {args.output}")

        if args.json:
            print(json.dumps(pr_info))

        return

    # Standard interactive mode
    info = get_current_bookmark_info(args.bookmark)

    if not info:
        print("No bookmarked commit found.", file=sys.stderr)
        return

    bookmarks = info.get("bookmarks", [])
    if not bookmarks:
        print("Current commit has no bookmarks.")
        return

    current_bookmark = bookmarks[0]

    # Check if it's a push-xxxx branch
    if not is_push_branch(current_bookmark):
        print(f"Bookmark '{current_bookmark}' is already well-named. Nothing to do.")
        return

    # Parse commit description
    description = info.get("description", "")
    prefix, title = parse_commit_description(description)
    topic = slugify_title(title)

    # Get stack position
    position, total = get_stack_position(current_bookmark)

    # Generate new name
    new_name = generate_branch_name(prefix, topic, position, total)
    suggested_pr_title = generate_pr_title(prefix, title, topic, position, total)

    print(f"\n📝 Commit: {description}")
    print(f"🔖 Current bookmark: {current_bookmark}")
    print(f"📍 Stack position: {position}/{total}")
    print(f"✨ New branch name: {new_name}")
    print(f"📋 Suggested PR title: {suggested_pr_title}\n")

    # Rename
    rename_bookmark(current_bookmark, new_name, args.dry_run)


if __name__ == "__main__":
    main()
